name: Caffeine workflow

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        make install
        pipenv install -e .
        python --version ; pip --version ; pipenv --version
        pipenv run ./scripts/version
    - name: Docker compose up 
      run: |
        make create-env
        make dco-up
    - name: Lint code
      run: |
        make lint
    - name: Test
      run: |
        make test

    - name: Setup nodejs
      uses: actions/setup-node@v1.1.0
    - name: Lint and test frontend
      run: |
        cd frontend
        yarn install
        yarn test
